version: "3"

networks:
  test:

services:
  mosquitto:
    image: matteocollina/mosca:latest
    ports:
      - 1883:1883
    networks:
      - test
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - test
      
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      #- KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      #- KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    networks:
      - test

  init-kafka:
    image: confluentinc/cp-kafka:latest
    entrypoint: [ '/bin/bash', '-c' ]
    command: "'kafka-topics --bootstrap-server kafka:9092 --create --if-not-exists --topic test1-kafka --replication-factor 1 --partitions 1;\
      kafka-topics --bootstrap-server kafka:9092 --create --if-not-exists --topic test2-kafka --replication-factor 1 --partitions 1;\
      kafka-topics --bootstrap-server kafka:9092 --list;'"
    depends_on:
      - kafka
      - mosquitto
    networks:
      - test

  kafka-mqtt-connector:
    build: ./app
    environment:
     - MQTT_HOST=mosquitto
     - MQTT_PORT=1883
     - MQTT_CLIENT_ID=mqtt-client-1
     - MQTT_QOS=2
     - KAFKA_HOST=kafka
     - KAFKA_PORT=9092
     - KAFKA_CLIENT_ID=testing-kafka-producer-1
     - TOPIC_MAPPING=test1-mqtt>>test1-kafka;test2-mqtt<<test2-kafka
    volumes:
     - "./app:/services"
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    depends_on:
     - kafka
     - mosquitto
     - init-kafka
    networks:
      - test
